# Generated by Django 2.2.6 on 2019-11-21 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191121_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_post', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 21, 17, 45, 25, 810651)),
        ),
    ]
